export const NEW_TASK = 'NEW_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const NEW_CATEGORY = 'NEW_CATEGORY';
export const START_POMODORO = 'START_POMODORO';
export const STOP_POMODORO = 'STOP_POMODORO';
export const PAUSE_POMODORO = 'PAUSE_POMODORO';
